### PR TITLE
304 csv export

### PR DESCRIPTION
**Pull request by ali-7**
#### Issues this PR relates to
#304 
---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

### CODE REVIEW

**Comment by ali-7** [comment]
Hey @thejoefriel 
the table's data are different from the excel file - tried to choose the right keys from them, put not all the keys are in the data like the excel. 
Also, there's no Earn Groups keys in the excel - so i exported the data from the table.

All the pages exports are working - just need to make sure it's the right data.

**Comment by ali-7** [comment]
yeah and also,  exports Earn Groups - Spend Partners from the static data

**Comment by thejoefriel** [comment]
Great thanks @ali-7 ! @RamyAlshurafa can you have a quick look at this as well please? It may be we need to send a few more fields to the front in the initial query so they are there for the data export

**Comment by ali-7** [comment]
Hi @thejoefriel 

added exports to members and transactions tables as an earn group and the transactions table as a spend partner.
but they don't have any keys in the excel sheet (just tempo-staff-keys), so I used the data from the tables and the quires. 

this pr only needs the missing data, I added them on each export so it will be easily added after modifying the queries. (it just needs the values)

**Pull request merged**
