### PR TITLE
fix spend dummy data

### PR DESCRIPTION
**Pull request by ashatat**
#751

for members, the issue was on the dummy data, so I fixed it

in programmes table 
image

spent % calculated as follows
2 tc have been spent / 12 tc have been earned/giftedin to members (10 earned and 2 gifted)

### CODE REVIEW

**Comment by thejoefriel** [comment]
> #751
> 
> for members, the issue was on the dummy data, so I fixed it
> 
> in programmes table
> image
> 
> spent % calculated as follows
> 2 tc have been spent / 12 tc have been earned/giftedin to members (10 earned and 2 gifted)

Ah ok, yeah I understand you. However, shouldn't this then also be 16%? At the moment you get a different spend % in the programmes section for Programme 1 vs what you see when you then click to view Programme 1. I think these should be consistent. 

http://www.clipular.com/posts/5056156337438720?k=ofPwXH83IdpQgbkpJAzH6QLHmjg

**Comment by ashatat** [comment]
@thejoefriel  can you demonstrate what it should be?

btw in the individual programme page, there is a different explanation for the spend I got it from issue #603 document
which says:
```md
INDIVIDUAL PROGRAMME PAGE
% SPENT WITH SPEND VENUES – the % of Time Credits that have been earned in a programme that have been spent with Spend Venues
% SPENT WITH EARN GROUPS – the % of Time Credits that have been earned in a programme that have been spent with Earn Groups
```

**Comment by thejoefriel** [comment]
> @thejoefriel can you demonstrate what it should be?
> 
> btw in the individual programme page, there is a different explanation for the spend I got it from issue #603 document
> which says:
> 
> ```lisp
> INDIVIDUAL PROGRAMME PAGE
> % SPENT WITH SPEND VENUES – the % of Time Credits that have been earned in a programme that have been spent with Spend Venues
> % SPENT WITH EARN GROUPS – the % of Time Credits that have been earned in a programme that have been spent with Earn Groups
> ```

Yeah messaged you on Slack. Whoever did the helper text put in the wrong text, so if you followed that it would be misleading 😓 

For Programmes % SPENT should be the % of Time Credits that have been earned in a programme that have been spent (with Earn Groups or Spend Venues)
i.e. the % of Programme Time Credits given out by Earn Groups that are associated with the Programme that have been spent (with earn group or spend venue)

**Comment by thejoefriel** [comment]
The correct explanation had been included in both issues  https://github.com/yalla-coop/tempo/issues/607 and https://github.com/yalla-coop/tempo/issues/605

But appreciate this may have been missed if using the helper text on the front end as the guide

**Pull request merged**
