### PR TITLE
add travis config

### PR DESCRIPTION
**Pull request by ashatat**
#193

#### Issues this PR relates to

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

### CODE REVIEW

**Comment by thejoefriel** [comment]
Looks good and everything is working for me. Just one question, should we have anything run after script to close the database. I know that's what we do on mongo but unsure whether postgresql is different?

**Comment by thejoefriel** [comment]
Also do we need to tell travis to do an npm install?

Again these questions are more from curiosity rather than me knowing!

**Comment by ashatat** [comment]
Travis by default do npm install, and cache the node_modules, so it runs faster 
travis install and run psotgresql server each time it runs the test, and when it's done it exit all processes including the postgresql, so i don't think there is a meaning of closing the connection when the whole process will die

**Comment by thejoefriel** [comment]
Perfect @ashatat thanks for that :)

**Pull request merged**
