### PR TITLE
fix programme tc tracking flow

### LINKED ISSUE #836: Programme TC Tracking Issues
- [ ] Programme Time Credits that are in an Earn Groups account, at the time when they are moved to another programme, are then reported as the new programme's Time Credits when earned or spent. These should remain tied to the original programme.  Video here: https://drive.google.com/file/d/1iSxuBrYQBoq8dS9enluxdIyzAGqTUyn8/view?usp=sharing

Confirmation again of flow: https://whimsical.com/DNheGSu2kR1v5NvYt5ze9F
To confirm:
- Any TCs issued by a programme (or no programme) are linked to that programme until they are spent. So if prog 1 issues 10 TCs, those TCs will always be linked to prog 1 and count to its data until they are spent by a member at either a spend venue or earn group 

- Any TCs accepted by an earn group from a member are then either linked to the programme that earn group is currently part of OR no programme (if the earn group isn't part of an earn group). This link stays until they are spent. 

So whenever a TC is issued or accepted, whichever programme (or no programme) it is linked to, it stays that way until it is spent, which is when it's journey with that link finishes.

- [ ] A member spent 5 TC with a Spend Venue (you can see proof of this here: http://www.clipular.com/posts/5661319813136384?k=y7ZqNXEiSWOMOaR9FkeSIk2Br1w). In the transaction exports for the two programmes on the system, they are both showing Number of Programme TC as 5. It should be 2 in one and 3 in the other

- [ ] Not to do with tracking but might as well be fixed in this issue since it's part of the same area :) Need to ensure we round numbers to the nearest integer to prevent log decimal numbers like this: http://www.clipular.com/posts/4695590645268480?k=LpmT3wX0XcZQsdF4qB75x9oLlA8

### PR DESCRIPTION
**Pull request by ashatat**
fix #836 

@thejoefriel  @dupreesi  
I have removed converting tc to new programme when giving out tc
so now the tracking should be working as the wimsicles 
would appreciate if you do manual testing to verify that it is working as it should

### CODE REVIEW

**Comment by thejoefriel** [comment]
@dupreesi can you check this as well please following this document? 🙏 
[Data Testing Plan.pdf](https://github.com/yalla-coop/tempo/files/4942167/Data.Testing.Plan.pdf)

**Comment by ashatat** [comment]
> * [ ]  Accepted Time Credits isn't right. 5 TCs from Programme A were spent with EG1 which is part of Programme A. 2 TCs from Programme A were spent with EG2, which isn't part of Programme A. So it should show 5 TCs accepted, but at the moment it's showing 7 TCs accepted: http://www.clipular.com/posts/6658725706989568?k=wGiWuV6pT1on5M-xcXg9-mamHAk
> 
> Apart from this I think it's working well though! I've asked @dupreesi to do another check tomorrow

@thejoefriel   so you want the tc track to be counted as spent from programme B?
so if 2 tc a member earned from programme A, and he spend them with an earnGroup that is part of programme B, so they should not counted as spent with programme A, and counted to be spent as programme A?

**Comment by thejoefriel** [comment]
Hey ahmed, no so they are spent from programme a. How you've done this is 100% correct. However 2 TCs were accepted by a earn group in a different programme, so those two count to the accepted stat of prog b (accepted and spent are different)

Spent is always the end of a tc journey. This is the final stat of that tc we attribute to prog a. 
Accept is the start of a tc journey when we attribute that tc to a bee programme. So this is the first stat of that tc we attribute to prog b

**Comment by thejoefriel** [comment]
Hi, so the Time Credits accepted stat is correct in the dashboard, but isn't right int the table. In this example Barnet Together has accepted 94 credits, but only 2 while part of this programme, and 92 while part of another programme. You can see the total accepted in the stats is correct: http://www.clipular.com/posts/5131123649413120?k=plRLcNNYfAGCiU35jiMGH2G480I 

So the time credits accepted for them in this table should be 2 and time credits accepted for them in the other programme table should be 92 (it is currently showing it as 0: http://www.clipular.com/posts/6301994413981696?k=0FuR8bJdJ3UQo7YXtHjI2Q7uiVw)

**Pull request merged**
